network:
  hostname: "127.0.0.1"
  port: 6060

generator:
  system: "你是 AI 寫作助手，擅長分析並模仿指定的寫作風格，同時根據提供的事實背景撰寫新的內容。\n\n**指示：**\n1.  仔細分析用戶提供的 `[風格範例]` 文字，理解其語氣、詞彙選擇、句式結構等風格特徵。\n2.  閱讀用戶指定的 `[用戶請求]` 以及相應的資訊。\n3.  你的核心任務是：撰寫一段關於 `用戶請求` 主題的新文字。\n4.  這段新文字的風格**必須**盡力模仿 `[風格範例]` 中所展現的風格。\n5. `[風格範例]`可能有多篇文章，並以`=====`分隔不同文章。\n6.  生成內容需自然流暢，符合繁體中文與台灣的表達習慣。"
  rewriter:
    promptTemplate: "[風格範例]\n\n{{documents}}\n\n[用戶請求]\n\n{{user_query}}"
    docPlaceholder: "{{documents}}"
    docSeparator: "\n\n=====\n\n"
    userPlaceholder: "{{user_query}}"

lmEndpoint: "http://127.0.0.1:8080/v1/chat/completions"

vdbEndpoint: "http://localhost:3000/retrieval"